export default [
	{
		userId: 1,
		email: 'test1@test.com',
		firstName: 'TestFirst1',
		lastName: 'TestLast1',
		username: 'testusername1',
		avatarUrl: '/images/site/Scott.JPG',
		date: 'Dec 1, 2021',
	},
	{
		userId: 2,
		email: 'test2@test.com',
		firstName: 'TestFirst2',
		lastName: 'TestLast2',
		username: 'testusername2',
		avatarUrl: '/images/site/Scott.JPG',
		date: 'Dec 2, 2021',
	},
	{
		userId: 3,
		email: 'test3@test.com',
		firstName: 'TestFirst3',
		lastName: 'TestLast3',
		username: 'testusername3',
		avatarUrl: '/images/site/Scott.JPG',
		date: 'Dec 3, 2021',
	},
	{
		userId: 4,
		email: 'test4@test.com',
		firstName: 'TestFirst4',
		lastName: 'TestLast4',
		username: 'testusername4',
		avatarUrl: '/images/site/Scott.JPG',
		date: 'Dec 4, 2021',
	},
	{
		userId: 5,
		email: 'test5@test.com',
		firstName: 'TestFirst5',
		lastName: 'TestLast5',
		username: 'testusername5',
		avatarUrl: '/images/site/Scott.JPG',
		date: 'Dec 5, 2021',
	},
];
