export default [
	{
		userId: 1,
		email: 'test1@test.com',
		firstName: 'TestFirst1',
		lastName: 'TestLast1',
		username: 'testusername1',
		avatarUrl: '/images/site/Scott.JPG',
		date: 'Dec 1, 2021',
	},
	{
		userId: 2,
		email: 'test2@test.com',
		firstName: 'TestFirst2',
		lastName: 'TestLast2',
		username: 'testusername2',
		avatarUrl: '/images/site/Scott.JPG',
		date: 'Dec 2, 2021',
	},
	{
		userId: 3,
		email: 'test3@test.com',
		firstName: 'TestFirst3',
		lastName: 'TestLast3',
		username: 'testusername3',
		avatarUrl: '/images/site/Scott.JPG',
		date: 'Dec 3, 2021',
	},
	{
		userId: 4,
		email: 'test4@test.com',
		firstName: 'TestFirst4',
		lastName: 'TestLast4',
		username: 'testusername4',
		avatarUrl: '/images/site/Scott.JPG',
		date: 'Dec 4, 2021',
	},
	{
		userId: 5,
		email: 'test5@test.com',
		firstName: 'TestFirst5',
		lastName: 'TestLast5',
		username: 'testusername5',
		avatarUrl: '/images/site/Scott.JPG',
		date: 'Dec 5, 2021',
	},
	{
		userId: 6,
		email: 'test6@test.com',
		firstName: 'TestFirst6',
		lastName: 'TestLast6',
		username: 'testusername6',
		avatarUrl: '/images/site/Scott.JPG',
		date: 'Dec 1, 2021',
	},
	{
		userId: 7,
		email: 'test7@test.com',
		firstName: 'TestFirst7',
		lastName: 'TestLast7',
		username: 'testusername7',
		avatarUrl: '/images/site/Scott.JPG',
		date: 'Dec 2, 2021',
	},
	{
		userId: 8,
		email: 'test8@test.com',
		firstName: 'TestFirst8',
		lastName: 'TestLast8',
		username: 'testusername8',
		avatarUrl: '/images/site/Scott.JPG',
		date: 'Dec 3, 2021',
	},
	{
		userId: 9,
		email: 'test9@test.com',
		firstName: 'TestFirst9',
		lastName: 'TestLast9',
		username: 'testusername9',
		avatarUrl: '/images/site/Scott.JPG',
		date: 'Dec 4, 2021',
	},
	{
		userId: 10,
		email: 'test10@test.com',
		firstName: 'TestFirst10',
		lastName: 'TestLast10',
		username: 'testusername10',
		avatarUrl: '/images/site/Scott.JPG',
		date: 'Dec 5, 2021',
	},
];
