export default [
	{
		imagePath:
			'/images/blogs/getting-started-with-vr-in-unity1/getting-started-vr.png',
		title: 'Unity C# Programmer',
		company: 'Company Inc.',
		date: 'Jan 20, 2022',
		city: 'Los Angeles, CA',
		country: 'United States',
		pay: '$45,000 - $75,000 / yr',
		hours: 'full',
		featured: true,
	},
	{
		imagePath:
			'/images/blogs/getting-started-with-vr-in-unity1/getting-started-vr.png',
		title: 'Unreal Engine Game Designer',
		company: 'Business Co.',
		date: 'Oct 30, 2021',
		city: 'Seattle, WA',
		country: 'United States',
		pay: '$40 / hr',
		hours: 'part',
		featured: false,
	},
	{
		imagePath:
			'/images/blogs/getting-started-with-vr-in-unity1/getting-started-vr.png',
		title: '3D Character Artist',
		company: 'Business Co.',
		date: 'Dec 11, 2021',
		city: 'Berlin',
		country: 'Germany',
		pay: '$500',
		hours: 'freelance',
		featured: false,
	},
	{
		imagePath:
			'/images/blogs/getting-started-with-vr-in-unity1/getting-started-vr.png',
		title: 'Unity C# Programmer',
		company: 'Company Inc.',
		date: 'Jan 20, 2022',
		city: 'Los Angeles, CA',
		country: 'United States',
		pay: '$45,000 - $75,000 / yr',
		hours: 'full',
		featured: false,
	},
	{
		imagePath:
			'/images/blogs/getting-started-with-vr-in-unity1/getting-started-vr.png',
		title: 'Unreal Engine Game Designer',
		company: 'Business Co.',
		date: 'Oct 30, 2021',
		city: 'Seattle, WA',
		country: 'United States',
		pay: '$40 / hr',
		hours: 'part',
		featured: false,
	},
	{
		imagePath:
			'/images/blogs/getting-started-with-vr-in-unity1/getting-started-vr.png',
		title: '3D Character Artist',
		company: 'Business Co.',
		date: 'Dec 11, 2021',
		city: 'Berlin',
		country: 'Germany',
		pay: '$500',
		hours: 'freelance',
		featured: false,
	},
	{
		imagePath:
			'/images/blogs/getting-started-with-vr-in-unity1/getting-started-vr.png',
		title: 'Unity C# Programmer',
		company: 'Company Inc.',
		date: 'Jan 20, 2022',
		city: 'Los Angeles, CA',
		country: 'United States',
		pay: '$45,000 - $75,000 / yr',
		hours: 'full',
		featured: false,
	},
	{
		imagePath:
			'/images/blogs/getting-started-with-vr-in-unity1/getting-started-vr.png',
		title: 'Unreal Engine Game Designer',
		company: 'Business Co.',
		date: 'Oct 30, 2021',
		city: 'Seattle, WA',
		country: 'United States',
		pay: '$40 / hr',
		hours: 'part',
		featured: false,
	},
	{
		imagePath:
			'/images/blogs/getting-started-with-vr-in-unity1/getting-started-vr.png',
		title: '3D Character Artist',
		company: 'Business Co.',
		date: 'Dec 11, 2021',
		city: 'Berlin',
		country: 'Germany',
		pay: '$500',
		hours: 'freelance',
		featured: false,
	},
	{
		imagePath:
			'/images/blogs/getting-started-with-vr-in-unity1/getting-started-vr.png',
		title: 'Unity C# Programmer',
		company: 'Company Inc.',
		date: 'Jan 20, 2022',
		city: 'Los Angeles, CA',
		country: 'United States',
		pay: '$45,000 - $75,000 / yr',
		hours: 'full',
		featured: false,
	},
	{
		imagePath:
			'/images/blogs/getting-started-with-vr-in-unity1/getting-started-vr.png',
		title: 'Unreal Engine Game Designer',
		company: 'Business Co.',
		date: 'Oct 30, 2021',
		city: 'Seattle, WA',
		country: 'United States',
		pay: '$40 / hr',
		hours: 'part',
		featured: false,
	},
	{
		imagePath:
			'/images/blogs/getting-started-with-vr-in-unity1/getting-started-vr.png',
		title: '3D Character Artist',
		company: 'Business Co.',
		date: 'Dec 11, 2021',
		city: 'Berlin',
		country: 'Germany',
		pay: '$500',
		hours: 'freelance',
		featured: false,
	},
];
